### ISSUE TITLE
能否增加从文件中enum时不重复

### ISSUE THREAD

**Issue by rebel117** [gangly/datafaker#18]
首先非常感谢大神的工具，非常非常好用，下面提个小小的建议

比如从文件a.txt中进行enum，里面有：
aaa
bbb
ccc
在生成3条 以内的数据时，aaa bbb  ccc 分别只出现一次
超过3条重复
或者如果指定了文件中enum且不重复的时候，生成的条数不能超过文件总行数

**Comment by gangly** [comment]
你好，可以这样实现：
用order_enum, 并指定worker数量为1，数据条数指定为文件中数据数

**Comment by rebel117** [comment]
嗯嗯，我去试试看，多谢多谢

**Comment by rebel117** [comment]
可以了，多谢大神
