### ISSUE TITLE
ES中的对象中嵌入对象，可以做到吗？谢谢

### ISSUE THREAD

**Issue by litianyiliwei** [gangly/datafaker#27]
"uid" : "2",
          "kdmc" : "考点名称",
          "kdjc" : "考点简称",
          "kdbsm" : "考点标识码",
          "sfbzhkd" : true,
          "kdjcsj" : "2018-02-01",
          "csxx" : {
            "kwbgsdh" : "考务办公室电话",
            "sjbgsdh" : "试卷保管（保密）室电话",
            "spjksdh" : "视频监考室电话",
            "sjbgsdhsxjsl" : 1,
            "sjffssxjsl" : 1,
            "kwbgssxjsl" : 1,
            "spjkssxjsl" : 1,
            "yybfssxjsl" : 1,
            "sjlzhtdsxjsl" : 1
          },
csxx这个字段可以写吗？感谢您的开源

**Comment by gangly** [comment]
目前不支持这种嵌套结构，后续会考虑改进

**Comment by litianyiliwei** [comment]
谢谢！不过，系统内部已经有了这种类型了。不知我们可以自定义以下系统类型不？
profile、simple_profile

**Comment by gangly** [comment]
说具体点呢， profile、simple_profile是什么

**Comment by litianyiliwei** [comment]
这是您这个文档datafaker/doc/zh_CN/数据构造规则.md，中的，其中profile、simple_profile就是我们讨论的系统内置的对象类型。如果，我们可以按照您系统中的profile，自定义数据类型就可以解决这个问题吧

人物信息相关
构造规则 | 含义 | 举例 | 备注
-- | -- | -- | --
name | 全名 | 单玉珍 |  
name_female | 男性全名 | 官平 |  
name_male | 女性全名 | 许颖 |  
first_name | 名 | 琴 |  
last_name | 姓 | 潘 |  
first_name_female | 女名 | 丽 |  
last_name_female | 女姓 | 王 |  
first_name_male | 男名 | 强 |  
last_name_male | 男姓 | 杨 |  
age | 人年龄 | 23 | 默认值 0-100
ssn | 身份证号 | 350526193807198690 |  
phone_number | 手机号 | 13926798387 |  
phonenumber_prefix | 手机号段 | 157 |  
profile | 档案信息 |   |  
simple_profile | 简单档案信息 | {'username': u'kcui', 'name': u'\u5415\u67f3', 'birthdate': datetime.date(1993, 3, 28), 'sex': 'F', 'address': u'\u9752\u6d77\u7701\u4e0a\u6d77\u53bf\u6881\u5e73\u5174\u5b89\u76df\u8defQ\u5ea7 532381', 'mail': u'juanpan@hotmail.com'}

**Comment by gangly** [comment]
嗯， 这个应该可以，你试试看

**Comment by litianyiliwei** [comment]
恩。需要您指点一下，怎么向profile一样，自定义数据类型，谢谢

**Comment by gangly** [comment]
> 恩。需要您指点一下，怎么向profile一样，自定义数据类型，谢谢

请更新到0.7.2版本
增加metaj参数，支持任意结构数据，包括json嵌套

**Comment by litianyiliwei** [comment]
感谢，果然是大神！
