### ISSUE TITLE
老哥，怎么生成一对多的数据关系

### ISSUE THREAD

**Issue by oneanime** [gangly/datafaker#53]
比如城市--地区
北京---地区（北京的地区随机）
前一个城市确定，然后后面的地区要是北京地区的，随机

**Comment by gangly** [comment]
@hadoopcode 可以将城市弄一个文件，地区弄一个文件，然后用order_enum关联，例如：
city.txt文件内容
北京
北京
北京
北京
四川
四川
四川
广东
广东

eara.txt文件内容
朝阳
昌平
海淀
大兴
成都
达州
绵阳
广州
中山

注意这两个文件相同行号中城市和地区应该对应，总行数一致
