### ISSUE TITLE
大数据量生成似乎有点困难

### ISSUE THREAD

**Issue by gdouzwt** [gangly/datafaker#57]
我试了生成 10 行数据插入 MySQL 可以，100 行偶尔成功，1000 行以上还未成功过。

**Comment by gangly** [comment]
具体问题是怎么的，报什么错

**Comment by gdouzwt** [comment]
一直卡在那里，没有响应

**Comment by tot123** [comment]
对,我这边 win10、py3.9.7 , 向mysql写入数据
10条 0.5s左右
15条 0.5s-81s左右
20条 0.5s 0.5s 39s
100条 531s
多线程写入速度不等时快时慢

**Comment by javalearner-yjj** [comment]
真特么垃圾
